### ISSUE TITLE
Release 0.6.0 to clojars?

### ISSUE THREAD

**Issue by cap10morgan** [bpoweski/consul-clojure#6]
Any chance of a 0.6.0 release getting pushed to clojars?

**Comment by bpoweski** [comment]
0.6.0-SNAPSHOT is up there now, but I'll cut a release.

Thanks!

**Comment by a4180p** [comment]
any news?

**Comment by bpoweski** [comment]
Sorry about the delay, ran into a PGP issue.  It's uploaded.
